spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management?characterEncoding=UTF8&useSSL=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  freemarker:
    suffix: .ftl
    charset: utf-8
    template-loader-path: classpath:page/
    cache: false
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lcj.manage.model
#  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 8080